//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference1
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OsobaCon", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceWebShop")]
    public partial class OsobaCon : object
    {
        
        private string ImePrezimeField;
        
        private int KolicinaField;
        
        private string KucniBrojField;
        
        private string MestoField;
        
        private int OsobaIdField;
        
        private string PostanskiBrojField;
        
        private string StaPorucujeteField;
        
        private string TelefonField;
        
        private string UlicaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ImePrezime
        {
            get
            {
                return this.ImePrezimeField;
            }
            set
            {
                this.ImePrezimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Kolicina
        {
            get
            {
                return this.KolicinaField;
            }
            set
            {
                this.KolicinaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string KucniBroj
        {
            get
            {
                return this.KucniBrojField;
            }
            set
            {
                this.KucniBrojField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mesto
        {
            get
            {
                return this.MestoField;
            }
            set
            {
                this.MestoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OsobaId
        {
            get
            {
                return this.OsobaIdField;
            }
            set
            {
                this.OsobaIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PostanskiBroj
        {
            get
            {
                return this.PostanskiBrojField;
            }
            set
            {
                this.PostanskiBrojField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StaPorucujete
        {
            get
            {
                return this.StaPorucujeteField;
            }
            set
            {
                this.StaPorucujeteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefon
        {
            get
            {
                return this.TelefonField;
            }
            set
            {
                this.TelefonField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ulica
        {
            get
            {
                return this.UlicaField;
            }
            set
            {
                this.UlicaField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Porucbenica", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceWebShop")]
    public partial class Porucbenica : object
    {
        
        private string ImePrezimeField;
        
        private int KolicinaField;
        
        private string KucniBrojField;
        
        private string MestoField;
        
        private int OsobaIdField;
        
        private string PostanskiBrojField;
        
        private string StaPorucujeteField;
        
        private string TelefonField;
        
        private string UlicaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ImePrezime
        {
            get
            {
                return this.ImePrezimeField;
            }
            set
            {
                this.ImePrezimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Kolicina
        {
            get
            {
                return this.KolicinaField;
            }
            set
            {
                this.KolicinaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string KucniBroj
        {
            get
            {
                return this.KucniBrojField;
            }
            set
            {
                this.KucniBrojField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mesto
        {
            get
            {
                return this.MestoField;
            }
            set
            {
                this.MestoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OsobaId
        {
            get
            {
                return this.OsobaIdField;
            }
            set
            {
                this.OsobaIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PostanskiBroj
        {
            get
            {
                return this.PostanskiBrojField;
            }
            set
            {
                this.PostanskiBrojField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StaPorucujete
        {
            get
            {
                return this.StaPorucujeteField;
            }
            set
            {
                this.StaPorucujeteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefon
        {
            get
            {
                return this.TelefonField;
            }
            set
            {
                this.TelefonField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ulica
        {
            get
            {
                return this.UlicaField;
            }
            set
            {
                this.UlicaField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IWebShopService")]
    public interface IWebShopService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebShopService/VratiOsobe", ReplyAction="http://tempuri.org/IWebShopService/VratiOsobeResponse")]
        System.Threading.Tasks.Task<System.Collections.ObjectModel.Collection<ServiceReference1.OsobaCon>> VratiOsobeAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebShopService/PreuzmiOsobe", ReplyAction="http://tempuri.org/IWebShopService/PreuzmiOsobeResponse")]
        System.Threading.Tasks.Task<System.Collections.ObjectModel.Collection<ServiceReference1.OsobaCon>> PreuzmiOsobeAsync(ServiceReference1.Porucbenica os);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    public interface IWebShopServiceChannel : ServiceReference1.IWebShopService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    public partial class WebShopServiceClient : System.ServiceModel.ClientBase<ServiceReference1.IWebShopService>, ServiceReference1.IWebShopService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public WebShopServiceClient() : 
                base(WebShopServiceClient.GetDefaultBinding(), WebShopServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IWebShopService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WebShopServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(WebShopServiceClient.GetBindingForEndpoint(endpointConfiguration), WebShopServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WebShopServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(WebShopServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WebShopServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(WebShopServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WebShopServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<System.Collections.ObjectModel.Collection<ServiceReference1.OsobaCon>> VratiOsobeAsync()
        {
            return base.Channel.VratiOsobeAsync();
        }
        
        public System.Threading.Tasks.Task<System.Collections.ObjectModel.Collection<ServiceReference1.OsobaCon>> PreuzmiOsobeAsync(ServiceReference1.Porucbenica os)
        {
            return base.Channel.PreuzmiOsobeAsync(os);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IWebShopService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IWebShopService))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:50214/ServicePorudzbenica.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return WebShopServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IWebShopService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return WebShopServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IWebShopService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IWebShopService,
        }
    }
}
